import { AppError, AppErrorKind } from './errors.js';
import { Url } from './url.js';
import type { ApiResult, RequestOptions } from './types.js';
export type RequestInterceptor = (request: Request) => Request | Promise<Request>;
export type ResponseInterceptor = (response: Response) => Response | Promise<Response>;
export interface HttpClientOptions { readonly baseUrl?: string; readonly fetch?: typeof fetch; readonly requestInterceptors?: readonly RequestInterceptor[]; readonly responseInterceptors?: readonly ResponseInterceptor[]; readonly defaultTimeoutMs?: number; }
export class HttpClient {
  private readonly baseUrl: string; private readonly fetcher: typeof fetch; private readonly requestInterceptors: readonly RequestInterceptor[]; private readonly responseInterceptors: readonly ResponseInterceptor[]; private readonly defaultTimeoutMs: number;
  constructor(options: HttpClientOptions = {}) { this.baseUrl = options.baseUrl ?? ''; this.fetcher = options.fetch ?? globalThis.fetch.bind(globalThis); this.requestInterceptors = options.requestInterceptors ?? []; this.responseInterceptors = options.responseInterceptors ?? []; this.defaultTimeoutMs = options.defaultTimeoutMs ?? 30_000; }
  async request<T>(url: Url | string, body?: unknown, options: RequestOptions = {}): Promise<T> {
    const endpoint = typeof url === 'string' ? url : url.resolve([], options); const requestUrl = new URL(endpoint, this.baseUrl || globalThis.location?.origin).toString(); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), options.timeoutMs ?? this.defaultTimeoutMs); const headers = new Headers(options.headers); if (body !== undefined && !headers.has('content-type')) headers.set('content-type', 'application/json'); const request = new Request(requestUrl, { ...options, headers, body: body === undefined ? undefined : JSON.stringify(body), signal: options.signal ?? controller.signal });
    try { let prepared = request; for (const interceptor of this.requestInterceptors) prepared = await interceptor(prepared); let response = await this.fetcher(prepared); for (const interceptor of this.responseInterceptors) response = await interceptor(response); if (!response.ok) throw this.httpError(response); const payload: unknown = response.status === 204 ? undefined : await response.json(); if (options.parseEnvelope === false) return payload as T; return this.unwrap<T>(payload); } catch (error) { if (error instanceof AppError) throw error; throw AppError.fromUnknown(error); } finally { clearTimeout(timeout); }
  }
  private unwrap<T>(payload: unknown): T { if (payload && typeof payload === 'object' && 'success' in payload && 'data' in payload) { const result = payload as ApiResult<T>; if (!result.success) throw new AppError(AppErrorKind.PROTOCOL, result.message, { code: result.code, requestId: result.requestId }); return result.data; } return payload as T; }
  private httpError(response: Response): AppError { const kind = response.status === 401 ? AppErrorKind.UNAUTHORIZED : response.status === 403 ? AppErrorKind.FORBIDDEN : response.status === 429 ? AppErrorKind.RATE_LIMITED : response.status >= 500 ? AppErrorKind.SERVER : AppErrorKind.PROTOCOL; const retryAfter = Number(response.headers.get('retry-after')); return new AppError(kind, `HTTP request failed with status ${response.status}`, { status: response.status, retryAfterMs: Number.isFinite(retryAfter) ? retryAfter * 1000 : undefined }); }
}
